const products = [
    {
        id: 1,
        name: 'Leche Alpura',
        price: 27.00,
        description: 'Leche de vaca entera 1.5L',
        image: require('./Components/images/leche.png'),
    },
    {
        id: 2,
        name: 'Servilletas Petalo',
        price: 40.00,
        description: 'Servilletas de papel Petalo 500pzs',
        image: require('./Components/images/servilletas.png'),
    },
    {
        id: 3,
        name: 'Atún de aceite Dolores',
        price: 19.00,
        description: 'Atún de aceite en lata Dolores 200g',
        image: require('./Components/images/atun.png'),
    },
    {
        id: 4,
        name: 'Donas Bimbo',
        price: 25.00,
        description: 'Donas de azúcar Bimbo',
        image: require('./Components/images/donas.png'),
    },
    {
        id: 5,
        name: 'Desodorante Axe de Chocolate',
        price: 50.00,
        description: 'Desodorante en aerosol',
        image: require('./Components/images/axe.png'),
    },
    {
        id: 6,
        name: '12 Huevos frescos',
        price: 35.00,
        description: 'Huevos de gallina',
        image: require('./Components/images/huevos.png'),
      },
      {
        id: 7,
        name: '1.5kg Arroz blanco',
        price: 28.00,
        description: 'Arroz blanco para cocinar',
        image: require('./Components/images/arroz.png'),
      },
      {
        id: 8,
        name: 'Jabón de manos Dove',
        price: 32.00,
        description: 'Jabón líquido para manos',
        image: require('./Components/images/jabon.png'),
      },
      {
        id: 9,
        name: 'Pasta de dientes Colgate',
        price: 25.00,
        description: 'Pasta de dientes para uso diario',
        image: require('./Components/images/pasta.png'),
      },
      {
        id: 10,
        name: 'Detergente líquido Ariel',
        price: 40.00,
        description: 'Detergente para lavar ropa',
        image: require('./Components/images/detergente.png'),
      },
      {
        id: 11,
        name: '1/2kg Manzanas rojas',
        price: 20.00,
        description: 'Manzanas rojas frescas',
        image: require('./Components/images/manzana.png'),
      },
      {
        id: 12,
        name: '1kg Plátanos',
        price: 15.00,
        description: 'Plátano Chiapas',
        image: require('./Components/images/platano.png'),
      },
      {
        id: 13,
        name: '1/2 Jitomates',
        price: 22.00,
        description: 'Jitomates rojos frescos',
        image: require('./Components/images/jitomate.png'),
      },
      {
        id: 14,
        name: 'Carne molida de res',
        price: 55.00,
        description: 'Carne molida de res fresca',
        image: require('./Components/images/res.png'),
      },
      {
        id: 15,
        name: '1kg Pechuga de Pollo',
        price: 150.00,
        description: 'Pechuga de pollo fresca',
        image: require('./Components/images/pechuga.png'),
      },
];

export default products;